import utime
from wheel import Wheel


TIMER0 = 0
TIMER1 = 1
TIMER2 = 2
CHANNEL0 = 0
CHANNEL1 = 1
CHANNEL2 = 2
CHANNEL3 = 3

LEVEL1 = 1
LEVEL2 = 2
LEVEL3 = 3
LEVEL4 = 4
LEVEL5 = 5
DEFAULT_LEVEL = LEVEL2

LEFT_FRONT = Wheel(19, 20, TIMER0, CHANNEL0, TIMER0, CHANNEL1) # 左前轮
LEFT_BACK = Wheel(15, 17, TIMER0, CHANNEL2, TIMER0, CHANNEL3) # 左后轮
RIGHT_FRONT = Wheel(33, 34, TIMER1, CHANNEL0, TIMER1, CHANNEL1) # 右前轮
RIGHT_BACK = Wheel(35, 30, TIMER1, CHANNEL2, TIMER1, CHANNEL3) # 右后轮

LEFT_FRONT.gear(DEFAULT_LEVEL)
LEFT_BACK.gear(DEFAULT_LEVEL)
RIGHT_FRONT.gear(DEFAULT_LEVEL)
RIGHT_BACK.gear(DEFAULT_LEVEL)
utime.sleep_ms(1000)

LEFT_FRONT.break_car()
LEFT_BACK.break_car()
RIGHT_FRONT.break_car()
RIGHT_BACK.break_car()
utime.sleep_ms(1000)

LEFT_FRONT.stop()
LEFT_BACK.stop()
RIGHT_FRONT.stop()
RIGHT_BACK.stop()
utime.sleep_ms(1000)

print('FINISH')
